### ISSUE TITLE
[META] Integrate with OpenSearch Settings

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-py#84]
### Is your feature request related to a problem?

Extensions may have their own settings that must be registered with OpenSearch.

Extensions may make use of OpenSearch settings and need to subscribe to changes in those settings.

### What solution would you like?

- [ ] A local copy of OpenSearch settings populated at initialization
- [ ] A `Setting` class porting the relevant settings creation portions of [`Setting`](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/settings/Setting.java)
- [ ] The same class porting the relevant transport-related portions of [`WriteableSetting`](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/settings/WriteableSetting.java)
- [ ] A `getSettings()` extension point on the Extension interface
- [ ] A handler for registering settings obtained from the above interface
- [ ] A handler for subscribing to and receiving setting updates

### What alternatives have you considered?

None; the above most closely resembles the Java SDK implementation which required multiple iterations to get right.

### Do you have any additional context?

The Java `WriteableSetting` constructor takes a `Setting<T>` object as a parameter with this `Setting` used in the extension. Given that we are not importing the Python class it is entirely reasonable to combine the functionality of the two classes.

**Comment by dblock** [comment]
@dbwiddis update this one with current status?

**Comment by dbwiddis** [comment]
It's up to date. The third bullet is partially complete but still doesn't have transport for the superclass.  I'll split it into two parts to make it more clear.
